title: Fang Xinyu's Homepage
page-top-title: Fang Xinyu
top-section-bg-text: Be what you wanna be
home-subtitle: Fang Xinyu&ensp;|&ensp;Trent Alex 方新宇
copyright-text: '&copy; Fang Xinyu 2023-2025. All Rights Reserved.'

